version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: sparkuser
      POSTGRES_PASSWORD: sparkpass
      POSTGRES_DB: ssparkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sparknet


  spark:
    image: bitnami/spark:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - sparknet
    depends_on:
      - postgres
    volumes:
      - ./data:/opt/data 

volumes:
  postgres_data:

networks:
  sparknet:
    driver: bridge