

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sparknet


  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - sparknet
    depends_on:
      - postgres
    volumes:
      - ./data:/opt/data 
      - ./spark_streaming_to_postgres.py:/opt/spark_streaming_to_postgres.py 
      - .env:/opt/.env

volumes:
  postgres_data:

networks:
  sparknet:
    driver: bridge