{
 "title": "Live heartBeat Streaming Copy",
 "description": "Dashboard showing the computational analysis of heart beats of customers/ clients",
 "time": { "from": "2025-05-09T16:14:32.000Z", "to": "2025-05-09T16:18:00.000Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Number of Patients",
   "type": "stat",
   "description": "This is the total number of patients that have active heart reading.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM heartbeats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Heart Rate by Patient ID",
   "type": "stat",
   "description": "This is the average heart rates per patient id ",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(heart_rate) FROM heartbeats GROUP BY patient_id, heart_rate ORDER BY MAX(heart_rate) ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Peaking Heart Rate with Time",
   "type": "stat",
   "description": "Shows the Highest heart rates with time.",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(heart_rate) FROM heartbeats GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Heart Rate Changes",
   "type": "timeseries",
   "description": "Visualize how heart rate changes for a single or multiple patients",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  patient_id,\r\n  heart_rate\r\nFROM heartbeats\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  }
 ]
}